name: Download jawiki

on:
  schedule:
    - cron: "0 10 * * 2"
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        files:
          - {
              file: "jawiki-latest-redirect.sql.gz",
              rss: "jawiki-latest-redirect.sql.gz-rss.xml",
              sqlite: "jawiki-latest-redirect.sqlite",
            }
          - {
              file: "jawiki-latest-page.sql.gz",
              rss: "jawiki-latest-page.sql.gz-rss.xml",
              sqlite: "jawiki-latest-page.sqlite",
            }
          - {
              file: "jawiki-latest-pagelinks.sql.gz",
              rss: "jawiki-latest-pagelinks.sql.gz-rss.xml",
              sqlite: "jawiki-latest-pagelinks.sqlite",
            }
          - {
              file: "jawiki-latest-linktarget.sql.gz",
              rss: "jawiki-latest-linktarget.sql.gz-rss.xml",
              sqlite: "jawiki-latest-linktarget.sqlite",
            }
          - {
              file: "jawiki-latest-categorylinks.sql.gz",
              rss: "jawiki-latest-categorylinks.sql.gz-rss.xml",
              sqlite: "jawiki-latest-categorylinks.sqlite",
            }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install mysql-to-sqlite3

      - name: Install pv
        run: |
          sudo apt-get update
          sudo apt-get install pv

      - name: Start MySQL
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "9.0"
          root-password: root
          my-cnf: |
            skip_innodb_doublewrite
            disable_log_bin
            innodb_log_writer_threads=OFF
            innodb_dedicated_server=ON
            innodb_flush_log_at_trx_commit=2
            sync_binlog=0
            autocommit=0

      - name: Get previous pubDate
        uses: actions/cache@v4
        with:
          path: prevPubDate.txt
          key: rss-${{matrix.files.file}}

      - name: Date to environment variable
        run: echo "PREV_PUB_DATE=$(cat prevPubDate.txt 2>/dev/null || echo 'Thu, 01 Jan 1970 11:45:14 GMT')" >> $GITHUB_ENV

      - name: Get RSS pubDate
        run: |
          PUB_DATE=$(
            wget -q -O - https://dumps.wikimedia.org/jawiki/latest/${{matrix.files.rss}} | 
            awk -F'<pubDate>|</pubDate>' '{if ($2 != "") print $2}'
          )
          echo "PUB_DATE=$PUB_DATE" >> $GITHUB_ENV

      - name: Download
        if: ${{env.PREV_PUB_DATE != env.PUB_DATE}}
        run: |
          wget -q -O temp.sql.gz https://dumps.wikimedia.org/jawiki/latest/${{matrix.files.file}}

      - name: Extract
        if: ${{env.PREV_PUB_DATE != env.PUB_DATE}}
        run: |
          7z x temp.sql.gz

      - name: Import sql to mysql
        if: ${{env.PREV_PUB_DATE != env.PUB_DATE}}
        run: |
          mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS jawiki;"
          pv -f temp.sql | mysql -u root -proot jawiki

      - name: Export to sqlite
        if: ${{env.PREV_PUB_DATE != env.PUB_DATE}}
        run: |
          mysql2sqlite -f ${{matrix.files.sqlite}} -d jawiki -u root --mysql-password root

      - name: Compress
        if: ${{env.PREV_PUB_DATE != env.PUB_DATE}}
        run: |
          7z a ${{matrix.files.sqlite}}.7z ${{matrix.files.sqlite}}

      - name: Upload Artifact
        if: ${{env.PREV_PUB_DATE != env.PUB_DATE}}
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.files.sqlite}}.7z
          path: ${{matrix.files.sqlite}}.7z
          if-no-files-found: error

  release:
    needs: download
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Get Date
        run: echo "DATE=$(TZ=JST-9 date '+%Y.%-m.%-d')" >> $GITHUB_ENV

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts/
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.DATE }}
          name: ${{ env.DATE }}
          body: ${{ env.DATE }}
          files: |
            ./artifacts/*
