name: Download jawiki

on:
  schedule:
    - cron: "17 17 6,21 * *"
  workflow_dispatch:

env:
  RELEASE_API: https://api.github.com/repos/nakanishi123/wikipedia-golf/releases/latest

jobs:
  download:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        files:
          - {
              file: "jawiki-latest-redirect.sql.gz",
              rss: "jawiki-latest-redirect.sql.gz-rss.xml",
              sqlite: "jawiki-latest-redirect.sqlite",
            }
          - {
              file: "jawiki-latest-page.sql.gz",
              rss: "jawiki-latest-page.sql.gz-rss.xml",
              sqlite: "jawiki-latest-page.sqlite",
            }
          - {
              file: "jawiki-latest-pagelinks.sql.gz",
              rss: "jawiki-latest-pagelinks.sql.gz-rss.xml",
              sqlite: "jawiki-latest-pagelinks.sqlite",
            }
          - {
              file: "jawiki-latest-linktarget.sql.gz",
              rss: "jawiki-latest-linktarget.sql.gz-rss.xml",
              sqlite: "jawiki-latest-linktarget.sqlite",
            }
          - {
              file: "jawiki-latest-categorylinks.sql.gz",
              rss: "jawiki-latest-categorylinks.sql.gz-rss.xml",
              sqlite: "jawiki-latest-categorylinks.sqlite",
            }
    steps:
      - uses: actions/checkout@v4

      - name: Checkout mysql2sqlite
        uses: actions/checkout@v4
        with:
          repository: "mysql2sqlite/mysql2sqlite"
          path: "mysql2sqlite"

      - name: Get previous pubDate
        uses: actions/cache@v4
        with:
          path: prevPubDate.txt
          key: ${{matrix.files.file}}-prevPubDate.txt

      - name: Get RSS pubDate and set UPDATED
        run: |
          PUB_DATE=$(
            wget -q -O - https://dumps.wikimedia.org/jawiki/latest/${{matrix.files.rss}} | 
            awk -F'<pubDate>|</pubDate>' '{if ($2 != "") print $2}'
          )
          echo "PUB_DATE=$PUB_DATE" >> $GITHUB_ENV

          PREV_PUB_DATE=$(cat prevPubDate.txt 2>/dev/null || echo '😊')
          if [ "$PREV_PUB_DATE" != "$PUB_DATE" ]; then
            echo "UPDATED=UPDATED" >> $GITHUB_ENV
          else
            echo "UPDATED=" >> $GITHUB_ENV # empty if false
          fi

      - name: Make release_body.rtxt (For Release Body)
        run: |
          mkdir -p artifacts
          echo "| ${{matrix.files.file}} | ${{env.PUB_DATE}} | ${{env.UPDATED}} |" >> artifacts/release_body.rtxt.${{matrix.files.file}}

      - name: Download
        if: ${{env.UPDATED}}
        run: |
          wget -q -O temp.sql.gz https://dumps.wikimedia.org/jawiki/latest/${{matrix.files.file}}

      - name: Extract
        if: ${{env.UPDATED}}
        run: |
          7z x temp.sql.gz
          rm temp.sql.gz

      - name: Convert by mysql2sqlite.sh
        id: mysql2sqlite-sh
        if: ${{env.UPDATED}}
        continue-on-error: true
        run: |
          mysql2sqlite/mysql2sqlite temp.sql | sqlite3 ${{matrix.files.sqlite}}

      - uses: actions/setup-python@v5
        if: ${{env.UPDATED && steps.mysql2sqlite-sh.outcome == 'failure'}}
        with:
          python-version: "3.12"

      - name: Install dependencies for python mysql2sqlite
        if: ${{env.UPDATED && steps.mysql2sqlite-sh.outcome == 'failure'}}
        run: |
          pip install mysql-to-sqlite3
          sudo apt-get update
          sudo apt-get install pv

      - name: Start MySQL
        if: ${{env.UPDATED && steps.mysql2sqlite-sh.outcome == 'failure'}}
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "9.0"
          root-password: root
          my-cnf: |
            skip_innodb_doublewrite
            disable_log_bin
            innodb_log_writer_threads=OFF
            innodb_dedicated_server=ON
            innodb_flush_log_at_trx_commit=2
            sync_binlog=0

      - name: Import sql to mysql
        if: ${{env.UPDATED && steps.mysql2sqlite-sh.outcome == 'failure'}}
        run: |
          mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS jawiki;"
          pv -f temp.sql | mysql -u root -proot jawiki

      - name: Export to sqlite
        if: ${{env.UPDATED && steps.mysql2sqlite-sh.outcome == 'failure'}}
        run: |
          mysql2sqlite -f ${{matrix.files.sqlite}} -d jawiki -u root --mysql-password root

      - name: Compress and split
        if: ${{env.UPDATED}}
        run: |
          7z a ${{matrix.files.sqlite}}.7z ${{matrix.files.sqlite}}

          filesize=$(stat --format="%s" ${{matrix.files.sqlite}}.7z)
          if((filesize <= 2147483648)); then
            mv ${{matrix.files.sqlite}}.7z artifacts/
          else
            split --numeric-suffixes=1 -a 3 -b 2000m ${{matrix.files.sqlite}}.7z artifacts/${{matrix.files.sqlite}}.7z.
          fi

      - name: Download Release when not updated
        if: ${{!env.UPDATED}}
        run: |
          files=$(wget -qO- ${{env.RELEASE_API}} | jq -r '.assets[] | select(.name | startswith("${{matrix.files.sqlite}}")) | .browser_download_url')
          for file in $files; do
            wget -P artifacts $file
          done

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.files.sqlite}}.7z
          path: artifacts/*
          if-no-files-found: error

      - name: Save pubDate
        run: echo ${{env.PUB_DATE}} > prevPubDate.txt

      - name: Save pubDate
        uses: actions/cache/save@v4
        with:
          path: prevPubDate.txt
          key: ${{matrix.files.file}}-prevPubDate.txt

  release:
    needs: download
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Get Date
        run: echo "DATE=$(TZ=JST-9 date '+%Y.%-m.%-d')" >> $GITHUB_ENV

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts/
          merge-multiple: true

      - name: Make Release Body
        run: |
          echo "RELEASE_TEXT<<EOF"            >> $GITHUB_ENV
          echo "## wikipedia jawiki"          >> $GITHUB_ENV
          echo ""                             >> $GITHUB_ENV
          echo "| File | Date | Updated |"    >> $GITHUB_ENV
          echo "| ---- | ---- | ------- |"    >> $GITHUB_ENV
          cat ./artifacts/release_body.rtxt.* >> $GITHUB_ENV
          echo "EOF"                          >> $GITHUB_ENV

          rm ./artifacts/release_body.rtxt.*

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.DATE }}
          name: ${{ env.DATE }}
          body: ${{ env.RELEASE_TEXT }}
          files: |
            ./artifacts/*
